### PR TITLE
Updated Installation.rst

### PR DESCRIPTION
**Pull request by ChrisJon02**
The download links of PHP.net in the Installation.rst(Getting Started/Installation.rst) are not working. They're showing 404 errors.
Updated the download links of all the servers with their latest versions.

### CODE REVIEW

**Comment by JediKev** [comment]
@ChrisJon02 

Thank you for submitting changes however PHP 8.2 is not supported yet and you have three commits for a handful of changes. I will rewrite this pull and update the docs soon.

Cheers.

**Comment by ChrisJon02** [comment]
So will you merge my PR?
I'm very curious because it's my first PR

**Comment by JediKev** [comment]
@ChrisJon02 

Unfortunately no, I'm going to rewrite it. You have 3 commits for a handful of changes (not good - should only be one commit) and PHP 8.2 is not supported so it does not need to be linked in the docs (until it's actually supported). It will only confuse people further and make them think we support PHP 8.2.

I will make a new pull soon with the appropriate changes.

Cheers.

**Comment by ChrisJon02** [comment]
@JediKev 

well, thank you for letting me know that there should be only 1 commit

**Comment by JediKev** [comment]
@ChrisJon02 

No worries. You _can_ have multiple commits but only if it's like different sets of changes that are related. Like [this](https://github.com/osTicket/docs/pull/144) for example.

Cheers.

**Comment by ChrisJon02** [comment]
@JediKev  

Got it.   Thank you

**Pull request closed without merging**
